### PR TITLE
Get older version 0.9.42

### PR DESCRIPTION
**Pull request by synapticarbors**
DO NOT MERGE INTO MASTER!!

According to https://github.com/conda-forge/gap-feedstock/issues/1#issuecomment-279237244, an `0.9.42` branch needs to be created and then we can merge this PR into that branch. 

Resolves https://github.com/conda-forge/slacker-feedstock/issues/8

### CODE REVIEW

**Comment by synapticarbors** [comment]
@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
@synapticarbors as a core member you should have all that is needed to create the `branch`, if you are having trouble with that please let me know and I can do that for you.

**Comment by synapticarbors** [comment]
When I tried, I get an error:

```
$ git clone https://github.com/conda-forge/slacker-feedstock.git
Cloning into 'slacker-feedstock'...
remote: Enumerating objects: 73, done.
remote: Total 73 (delta 0), reused 0 (delta 0), pack-reused 73
Unpacking objects: 100% (73/73), done.
$ cd slacker-feedstock/
$ git checkout -b 0.9.42
Switched to a new branch '0.9.42'
$ git push -u origin 0.9.42
remote: Permission to conda-forge/slacker-feedstock.git denied to synapticarbors.
fatal: unable to access 'https://github.com/conda-forge/slacker-feedstock.git/': The requested URL returned error: 403
```

**Comment by ocefpaf** [comment]
Just bumped your rights. @synapticarbors can you try again?

**Comment by synapticarbors** [comment]
@ocefpaf - Works now.

**Comment by ocefpaf** [comment]
> @ocefpaf - Works now.

You should also have access for the Dbox paper and be on the meeting google calendar list. Let me know if those are OK on your side.
(We have a meeting tomorrow BTW.)

**Comment by synapticarbors** [comment]
Can you point me to where I can find those items?

**Comment by ocefpaf** [comment]
> Can you point me to where I can find those items?

I guess the former you can try to log on Dropbox paper and see if you have conda-forge docs folder there. Same thing with the Google calendar.

If you don't have those send me your proffered e-mail and I'll add you.

**Pull request merged**
